In [9]:
import gymnasium as gym

envs = gym.make_vec("Hopper-v5", num_envs=16, vectorization_mode="sync") #wrappers=(gym.wrappers.TimeAwareObservation,))
# envs = gym.wrappers.vector.ClipReward(envs, min_reward=0.2, max_reward=0.8)
state, info = envs.reset()


In [10]:
info

{'x_position': array([ 0.00475192, -0.00460625,  0.00347442,  0.00489697,  0.00077178,
         0.00047879,  0.00226332, -0.0048374 , -0.00049919,  0.00095829,
        -0.00482584,  0.00281093,  0.00206797, -0.00012012, -0.0031364 ,
        -0.00110096]),
 '_x_position': array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True]),
 'z_distance_from_origin': array([-9.81253807e-04, -1.72343394e-03, -4.03278180e-03,  5.33785591e-04,
         8.52779870e-04, -2.80178007e-03,  4.78320978e-03, -4.52251611e-04,
         2.50688871e-03, -4.61085739e-03, -2.14853478e-03,  3.28168344e-04,
        -2.03319339e-03,  4.18351843e-04,  1.38730193e-05, -3.67001202e-03]),
 '_z_distance_from_origin': array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True])}

In [11]:
state

array([[ 1.24901875e+00, -2.92719788e-03,  1.78350440e-03,
         3.59902052e-03,  4.55040301e-03, -1.04846590e-03,
        -3.68232119e-03, -3.76634180e-03, -2.63891603e-03,
        -2.47268295e-03,  1.37719765e-03],
       [ 1.24827657e+00, -5.90692855e-04, -1.04681955e-04,
         3.96376577e-03, -1.25008890e-04, -3.44829341e-03,
        -1.98484911e-03, -3.73579778e-04,  7.23529430e-04,
        -4.74048781e-04,  4.56532750e-03],
       [ 1.24596722e+00,  4.79460478e-03,  8.45201218e-04,
        -3.33799854e-03, -1.50665248e-03, -2.61922001e-03,
         2.46431914e-03,  2.05568018e-03, -2.73507910e-03,
         4.08493888e-04, -4.68815389e-03],
       [ 1.25053379e+00,  3.91502955e-03, -3.55490049e-04,
         1.28578234e-03, -1.20361303e-03, -2.79918184e-03,
         4.65956414e-03, -3.83518384e-04, -3.68811028e-03,
        -3.38385633e-04, -1.63786365e-03],
       [ 1.25085278e+00,  4.10798896e-03,  1.35187891e-03,
        -2.42922029e-03,  4.70743625e-03,  4.99902775e-03,
  

In [5]:
envs.action_space.shape

(16, 3)

In [12]:
import numpy as np

actions = np.zeros(shape=(16, 3))
states_, rewards, terminateds, truncateds, infos = envs.step(actions)

In [14]:
states_

array([[ 1.24867795e+00, -3.14333322e-03,  1.66035217e-03,
         3.36463696e-03,  4.57518629e-03, -6.51155179e-03,
        -8.16026811e-02, -4.42285005e-02, -2.48293770e-02,
        -4.91677975e-02,  4.36602792e-03],
       [ 1.24794934e+00, -6.87785183e-04, -7.70808458e-05,
         3.71726844e-03, -7.51970825e-05, -8.01835956e-03,
        -7.99061894e-02, -2.08714198e-02,  5.46510007e-03,
        -5.33221180e-02,  7.45015273e-03],
       [ 1.24567311e+00,  4.77500037e-03,  7.78778752e-04,
        -3.33106999e-03, -1.54351307e-03, -3.06664777e-03,
        -7.59940926e-02, -5.74084016e-03, -1.23673220e-02,
         1.19833804e-03, -4.54433981e-03],
       [ 1.25025798e+00,  3.88171912e-03, -3.77851239e-04,
         1.20483199e-03, -1.21234946e-03, -4.26898310e-03,
        -7.36388409e-02, -6.96614258e-03, -2.13199687e-03,
        -1.73712142e-02, -6.87339201e-04],
       [ 1.25055651e+00,  3.99762755e-03,  1.27708454e-03,
        -2.40562751e-03,  4.69766867e-03,  4.11219742e-03,
  

In [5]:
while not terminateds.any():
    states_, rewards, terminateds, truncateds, infos = envs.step(actions)

In [6]:
print(terminateds)
states_, rewards, terminateds, truncateds, infos = envs.step(actions)
print(terminateds)

[False False False False False False False False False False False  True
 False False False False]


AssertionError: self._autoreset_envs=array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False])

In [34]:
truncateds

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [12]:
states_.shape

(16, 12)

In [ ]:
from tqdm import tqdm
from agent import PPOPolicy, PPOPolicyBaseline
import gymnasium as gym
import ale_py
import torch
from torch.utils.tensorboard import SummaryWriter
import time


def evaluate_agent(agent, env, num_episodes=5):
    """
    Evaluate the agent's performance with epsilon=0 (no exploration).
    """

    total_rewards = []
    total_lengths = []

    for _ in range(num_episodes):
        state, _ = env.reset()
        episode_reward = 0
        episode_length = 0
        done = False

        while not done:
            action = agent.get_action(state)
            state_, reward, terminated, truncated, _ = env.step(action)
            done = terminated or truncated

            episode_reward += reward
            episode_length += 1
            state = state_

        total_rewards.append(episode_reward)
        total_lengths.append(episode_length)

    avg_reward = sum(total_rewards) / len(total_rewards)
    avg_length = sum(total_lengths) / len(total_lengths)

    return avg_reward, avg_length


if __name__ == "__main__":
    gym.register_envs(ale_py)

    n_steps = 1000000
    lr_actor = 1e-3  # seems to be the minimum that works
    device = torch.device("mps")
    eval_frequency = 50000
    eval_episodes = 5
    gamma = 0.95

    agent = PPOPolicyBaseline(device=device, lr_actor=lr_actor, gamma=gamma)

    s0 = torch.tensor([-0.04864075, 0.0167673, -0.00097064, -0.04351403])
    s1 = torch.tensor([0.0, 0.0, 0.2, 0.2])
    s2 = -torch.tensor([-0.04864075, 0.0167673, -0.00097064, -0.04351403])

    env = gym.make("CartPole-v1")
    writer = SummaryWriter(log_dir=f"runs/ppo_{int(time.time())}")
    state, info = env.reset()
    end = False
    running_episodes = 0
    episode_reward = 0
    episode_length = 0
    episode_loss = 0
    episode_grad_norm_actor = 0
    episode_grad_norm_critic = 0
    actions = []
    rewards = []
    states = []
    ends = []
    for i in tqdm(range(n_steps)):

        action = agent.get_action(state)
        state_, reward, terminated, truncated, info = env.step(action)
        end = terminated or truncated

        actions.append(action)
        states.append(state)
        rewards.append(reward)
        ends.append(end)

        episode_reward += reward
        episode_length += 1

        if i % 50 == 0:

            for enum, s in enumerate([s0, s1, s2]):
                debug_policy = torch.softmax(
                    agent.policy.forward(s),
                    dim=-1,
                )[0]

                debug_baseline = agent.baseline.forward(s)[0].detach()

                writer.add_scalar(
                    f"DebugPolicy/s{enum}",
                    debug_policy,
                    i,
                )

                writer.add_scalar(
                    f"DebugBaseline/s{enum}",
                    debug_baseline,
                    i,
                )

        if end:
            state, info = env.reset()
            end = False

            if running_episodes % 5 == 0:
                episode_loss, clip_loss, mse_loss, entropy_loss = agent.update_policy(
                    rewards, states, actions, ends
                )

                rewards = []
                actions = []
                states = []
                ends = []

            writer.add_scalar("Reward/episode", episode_reward, running_episodes)
            writer.add_scalar("Episode/Length", episode_length, running_episodes)
            writer.add_scalar("Episode/Loss", episode_loss, running_episodes)
            writer.add_scalar("Episode/clip_loss", clip_loss, running_episodes)
            writer.add_scalar("Episode/mse_loss", mse_loss, running_episodes)
            writer.add_scalar("Episode/entropy_loss", entropy_loss, running_episodes)
            writer.add_scalar(
                "DebugGrad/Episode Grad Norm actor",
                episode_grad_norm_actor / episode_length,
                running_episodes,
            )
            writer.add_scalar(
                "DebugGrad/Episode Grad Norm critic",
                episode_grad_norm_critic / episode_length,
                running_episodes,
            )

            running_episodes += 1
            episode_reward = 0
            episode_length = 0
            episode_grad_norm_actor = 0
            episode_grad_norm_critic = 0

        else:
            state = state_

        if i % eval_frequency == 0 and i > 0:
            print(f"Evaluating agent at step {i} and saving model...")
            torch.save(agent.policy.state_dict(), f"policy_gradient_model_{i}.pth")

            # Create a separate environment for evaluation to avoid affecting training
            eval_env = gym.make("CartPole-v1")
            avg_reward, avg_length = evaluate_agent(
                agent, eval_env, num_episodes=eval_episodes
            )

            writer.add_scalar("Evaluation/Average Reward", avg_reward, i)
            writer.add_scalar("Evaluation/Average Episode Length", avg_length, i)

            print(
                f"Evaluation results - Avg reward: {avg_reward:.2f}, Avg episode length: {avg_length:.2f}"
            )
            eval_env.close()

    print(f"Total episodes: {running_episodes}")
    # After training loop ends:
    torch.save(agent.policy.state_dict(), "policy_gradient_model_last.pth")

    # agent.state_encoder.load_state_dict(torch.load("dqn_model.pth"))
    # agent.state_encoder.to(device)
